language: php

php:
  - 7.1
  - 7.2

before_install:
  - echo "extension = yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar -O "$HOME/ocular.phar"
  
script:
  - vendor/bin/phpunit --coverage-clover cache/logs/clover.xml
  - phpstan analyze

after_success:
  - php "$HOME/ocular.phar" code-coverage:upload --format=php-clover cache/logs/clover.xml

