language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - mysql

install:
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar -O "$HOME/ocular.phar"
  
script:
  - vendor/bin/phpunit --coverage-clover cache/logs/clover.xml

after_success:
  - php "$HOME/ocular.phar" code-coverage:upload --format=php-clover cache/logs/clover.xml

